version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install Hadolint..."
      - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64
      - chmod +x hadolint
      - mv hadolint /usr/local/bin/
      - echo "Hadolint installed."
      - echo "Installing Docker..."
      - apt-get update
      - apt-get install -y docker.io

  build:
    commands:
      - hadolint Dockerfile
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 716308103419.dkr.ecr.eu-central-1.amazonaws.com
      - docker tag hello-python-flask:latest 716308103419.dkr.ecr.eu-central-1.amazonaws.com/hello-python-flask:latest
      - docker push 716308103419.dkr.ecr.eu-central-1.amazonaws.com/hello-python-flask:latest
