apiVersion: v1
kind: Service
metadata:
  name: hello-python-flask-service
spec:
  selector:
    app: hello-python-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer