name: Dockerfile Linting, Testing, and Push

on: [ push, pull_request ]

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Hadolint
      run: |
        wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        chmod +x hadolint
        sudo mv hadolint /usr/local/bin/

    - name: Run Hadolint
      run: hadolint Dockerfile

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-python-flask . 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag hello-python-flask ${{ secrets.DOCKER_USERNAME }}/hello-python-flask:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-python-flask

    - name: Clean up
      run: docker stop $(docker ps -q --filter ancestor=hello-python-flask) || true